# Generated by Django 5.0rc1 on 2024-03-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayscrochetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
