# Generated by Django 5.0rc1 on 2024-03-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayscrochetapp', '0003_item_is_preorder_item_preorder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='preorder_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
